"""Init

Revision ID: 115ff82e229f
Revises: 
Create Date: 2026-07-01 11:36:05.073298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '115ff82e229f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task_executions',
    sa.Column('execution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_args_hash', sa.String(length=64), nullable=False),
    sa.Column('celery_task_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index('ixz_celery_task_id', 'celery_task_executions', ['celery_task_id'], unique=False)
    op.create_index('ixz_task_execution_created_at', 'celery_task_executions', ['created_at'], unique=False)
    op.create_index('ixz_task_execution_status', 'celery_task_executions', ['status'], unique=False)
    op.create_index('ixz_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('domain_key', sa.Enum('generic', 'pharmacy', 'legal', name='domain_key'), server_default='generic', nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_en', sa.Text(), nullable=True),
    sa.Column('prompt_ar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_uuid')
    )
    op.create_index('ix_projects_domain_key', 'projects', ['domain_key'], unique=False)
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=False),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_uuid')
    )
    op.create_index('ix_asset_project_id', 'assets', ['asset_project_id'], unique=False)
    op.create_index('ix_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_uuid', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('message_uuid')
    )
    op.create_index('ix_chat_message_project_id', 'chat_messages', ['project_id'], unique=False)
    op.create_index('ix_chat_message_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_table('project_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user')
    )
    op.create_index('ix_project_users_project_id', 'project_users', ['project_id'], unique=False)
    op.create_index('ix_project_users_user_id', 'project_users', ['user_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_uuid', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_project_id', sa.Integer(), nullable=False),
    sa.Column('chunk_asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['chunk_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('chunk_uuid')
    )
    op.create_index('ix_chunk_asset_id', 'chunks', ['chunk_asset_id'], unique=False)
    op.create_index('ix_chunk_metadata_gin', 'chunks', ['chunk_metadata'], unique=False, postgresql_using='gin', postgresql_where=sa.text('chunk_metadata IS NOT NULL'))
    op.create_index('ix_chunk_project_id', 'chunks', ['chunk_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_project_id', table_name='chunks')
    op.drop_index('ix_chunk_metadata_gin', table_name='chunks', postgresql_using='gin', postgresql_where=sa.text('chunk_metadata IS NOT NULL'))
    op.drop_index('ix_chunk_asset_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_project_users_user_id', table_name='project_users')
    op.drop_index('ix_project_users_project_id', table_name='project_users')
    op.drop_table('project_users')
    op.drop_index('ix_chat_message_session_id', table_name='chat_messages')
    op.drop_index('ix_chat_message_project_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_asset_type', table_name='assets')
    op.drop_index('ix_asset_project_id', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_projects_domain_key', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ixz_task_name_args_celery_hash', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_status', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_created_at', table_name='celery_task_executions')
    op.drop_index('ixz_celery_task_id', table_name='celery_task_executions')
    op.drop_table('celery_task_executions')
    # ### end Alembic commands ###
