"""Curated product-level patches for the RAG_CORPUS_56 workbook."""
from __future__ import annotations

PRODUCT_PATCH_BY_FILE: dict[str, dict[str, object]] = {
    "02_panadol_cold_flu_day.txt": {
        "max_daily_dose": "8 caplets/day",
        "max_daily_dose_value": 8,
        "max_daily_dose_unit": "caplets",
    },
    "03_panadol_sinus_relief_pe.txt": {
        "max_daily_dose": "8 tablets/day",
        "max_daily_dose_value": 8,
        "max_daily_dose_unit": "tablets",
    },
    "04_cetal_cold_flu_day.txt": {
        "max_daily_dose": "8 caplets/day",
        "max_daily_dose_value": 8,
        "max_daily_dose_unit": "caplets",
    },
    "05_flurest_n.txt": {
        "max_daily_dose": "4 tablets/day",
        "max_daily_dose_value": 4,
        "max_daily_dose_unit": "tablets",
    },
    "06_congestal.txt": {
        "max_daily_dose": "6 tablets/day",
        "max_daily_dose_value": 6,
        "max_daily_dose_unit": "tablets",
    },
    "07_sine_up.txt": {
        "max_daily_dose": "4 tablets/day",
        "max_daily_dose_value": 4,
        "max_daily_dose_unit": "tablets",
    },
    "08_bradozen.txt": {
        "max_daily_dose": "4 tablets/day",
        "max_daily_dose_value": 4,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Otrivin|Strepsils|Panadol Advance",
        "pediatric_dose": "Not established. Not recommended in children unless prescribed.",
        "pediatric_min_age": "Not established",
        "pediatric_max_daily_dose": "",
    },
    "09_notussil.txt": {
        "max_daily_dose": "4 doses/day",
        "max_daily_dose_value": 4,
        "max_daily_dose_unit": "doses",
        "cross_selling": "Strepsils|Otrivin|Panadol Advance",
        "pediatric_dose": "Children >=2 years: Use age-appropriate dose per physician. Avoid under 2 years.",
        "pediatric_min_age": "2 years",
        "pediatric_max_daily_dose": "",
    },
    "10_tussigreen.txt": {
        "max_daily_dose": "4 doses/day",
        "max_daily_dose_value": 4,
        "max_daily_dose_unit": "doses",
        "cross_selling": "Strepsils|Otrivin|Panadol Advance",
        "pediatric_dose": "Children >=2 years: Use age-appropriate dose per physician. Avoid under 2 years.",
        "pediatric_min_age": "2 years",
        "pediatric_max_daily_dose": "",
    },
    "11_daflon_500.txt": {
        "max_daily_dose": "6 tablets/day",
        "max_daily_dose_value": 6,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Jeparilon",
        "pediatric_dose": "Safety and efficacy in children not established.",
        "pediatric_min_age": "Not established",
        "pediatric_max_daily_dose": "",
    },
    "12_daflon_1000.txt": {
        "max_daily_dose": "3 tablets/day",
        "max_daily_dose_value": 3,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Jeparilon",
        "pediatric_dose": "Safety and efficacy in children not established.",
        "pediatric_min_age": "Not established",
        "pediatric_max_daily_dose": "",
    },
    "13_controloc_20.txt": {
        "max_daily_dose": "2 tablets/day",
        "max_daily_dose_value": 2,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Gaviscon Advance|Motilium",
        "pediatric_dose": ">=5 years: 20 mg once daily for approved indications.",
        "pediatric_min_age": "5 years",
        "pediatric_max_daily_dose": "",
    },
    "14_jeparilon.txt": {
        "max_daily_dose": "4 tablets/day",
        "max_daily_dose_value": 4,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Daflon 500",
        "pediatric_dose": "Safety and efficacy in children not established.",
        "pediatric_min_age": "Not established",
        "pediatric_max_daily_dose": "",
    },
    "15_anaseziago.txt": {
        "max_daily_dose": "4 capsules/day",
        "max_daily_dose_value": 4,
        "max_daily_dose_unit": "capsules",
        "cross_selling": "Controloc 20",
        "pediatric_dose": "Not recommended in children under 12 years.",
        "pediatric_min_age": "12 years",
        "pediatric_max_daily_dose": "",
    },
    "01_panadol_paracetamol_500.txt": {
        "cross_selling": "Strepsils|Otrivin|Ventolin",
    },
    "16_adol_500.txt": {
        "cross_selling": "Strepsils|Otrivin",
    },
    "17_cataflam_25.txt": {
        "cross_selling": "Controloc 20|Gaviscon Advance",
        "pediatric_dose": "0.5-2 mg/kg/day in 2-3 divided doses. Max 150 mg/day.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "150 mg/day",
    },
    "18_brufen_400.txt": {
        "cross_selling": "Controloc 20|Gaviscon Advance",
        "pediatric_dose": "20-30 mg/kg/day in 3-4 divided doses. Max 40 mg/kg/day.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "40 mg/kg/day",
    },
    "19_antinal.txt": {
        "max_daily_dose": "8 capsules/day",
        "max_daily_dose_value": 8,
        "max_daily_dose_unit": "capsules",
        "cross_selling": "Enterogermina|Smecta",
        "pediatric_dose": ">=2 years: 200 mg every 6 hours.",
        "pediatric_min_age": "2 years",
        "pediatric_max_daily_dose": "",
    },
    "20_flagyl_500.txt": {
        "max_daily_dose": "4 tablets/day",
        "max_daily_dose_value": 4,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Enterogermina|Smecta",
        "pediatric_dose": "20-30 mg/kg/day in divided doses. Depends on indication.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "21_augmentin_1g.txt": {
        "max_daily_dose": "3 tablets/day",
        "max_daily_dose_value": 3,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Enterogermina|Smecta",
        "pediatric_dose": "25-45 mg/kg/day (amoxicillin component) in 2 divided doses.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "22_hibiotic_1g.txt": {
        "max_daily_dose": "2 tablets/day",
        "max_daily_dose_value": 2,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Enterogermina|Smecta",
        "pediatric_dose": "25-45 mg/kg/day (amoxicillin component) in 2 divided doses.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "23_zithrokan_500.txt": {
        "max_daily_dose": "1 tablet/day",
        "max_daily_dose_value": 1,
        "max_daily_dose_unit": "tablet",
        "cross_selling": "Enterogermina|Smecta",
        "pediatric_dose": "10 mg/kg once daily for 3 days or 10 mg/kg day 1 then 5 mg/kg/day days 2-5.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "24_ciprobay_500.txt": {
        "max_daily_dose": "2 tablets/day",
        "max_daily_dose_value": 2,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Enterogermina|Smecta",
        "pediatric_dose": "Use only for approved pediatric indications. Dose depends on indication.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "25_risek_20.txt": {
        "max_daily_dose": "2 capsules/day",
        "max_daily_dose_value": 2,
        "max_daily_dose_unit": "capsules",
        "cross_selling": "Gaviscon Advance|Motilium",
        "pediatric_dose": "0.7-3.3 mg/kg/day depending on indication.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "26_gaviscon.txt": {
        "max_daily_dose": "16 teaspoons/day",
        "max_daily_dose_value": 16,
        "max_daily_dose_unit": "teaspoons",
        "cross_selling": "Risek|Motilium",
        "pediatric_dose": "Not recommended under 12 years unless prescribed.",
        "pediatric_min_age": "12 years",
        "pediatric_max_daily_dose": "",
    },
    "27_motilium_10.txt": {
        "max_daily_dose": "3 tablets/day",
        "max_daily_dose_value": 3,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Gaviscon Advance|Risek|Smecta",
        "pediatric_dose": "Not routinely recommended in children. Use only if prescribed.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "28_buscopan.txt": {
        "max_daily_dose": "5 tablets/day",
        "max_daily_dose_value": 5,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Smecta|Motilium",
        "pediatric_dose": "6-12 years: 10 mg three times daily.",
        "pediatric_min_age": "6 years",
        "pediatric_max_daily_dose": "",
    },
    "29_concor_5.txt": {
        "max_daily_dose": "1 tablet/day",
        "max_daily_dose_value": 1,
        "max_daily_dose_unit": "tablet",
        "cross_selling": "Aspocid|Lipitor",
        "pediatric_dose": "Safety and efficacy in children not established.",
        "pediatric_min_age": "Not established",
        "pediatric_max_daily_dose": "",
    },
    "30_norvasc_5.txt": {
        "max_daily_dose": "1 tablet/day",
        "max_daily_dose_value": 1,
        "max_daily_dose_unit": "tablet",
        "cross_selling": "Aspocid|Lipitor",
        "pediatric_dose": "6-17 years: 2.5-5 mg once daily.",
        "pediatric_min_age": "6 years",
        "pediatric_max_daily_dose": "",
    },
    "31_glucophage_500.txt": {
        "max_daily_dose": "2550 mg/day",
        "max_daily_dose_value": 2550,
        "max_daily_dose_unit": "mg",
        "cross_selling": "Lipitor|Aspocid",
        "pediatric_dose": ">=10 years: Start 500 mg once daily, titrate. Max 2000 mg/day.",
        "pediatric_min_age": "10 years",
        "pediatric_max_daily_dose": "2000 mg/day",
    },
    "32_amaryl_2.txt": {
        "max_daily_dose": "8 mg/day",
        "max_daily_dose_value": 8,
        "max_daily_dose_unit": "mg",
        "cross_selling": "Glucophage",
        "pediatric_dose": "Not recommended in children.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "33_lipitor_20.txt": {
        "max_daily_dose": "80 mg/day",
        "max_daily_dose_value": 80,
        "max_daily_dose_unit": "mg",
        "pediatric_dose": ">=10 years: 10 mg once daily. Max 20 mg/day.",
        "pediatric_min_age": "10 years",
        "pediatric_max_daily_dose": "20 mg/day",
    },
    "34_plavix_75.txt": {
        "max_daily_dose": "75 mg/day",
        "max_daily_dose_value": 75,
        "max_daily_dose_unit": "mg",
        "cross_selling": "Lipitor",
        "pediatric_dose": "Use only under specialist supervision. Dose indication-specific.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "35_aspocid_75.txt": {
        "cross_selling": "Lipitor",
        "pediatric_dose": "Avoid under 16 years with viral illness. Otherwise only if prescribed.",
        "pediatric_min_age": "16 years",
        "pediatric_max_daily_dose": "",
    },
    "36_telfast_120.txt": {
        "max_daily_dose": "180 mg/day",
        "max_daily_dose_value": 180,
        "max_daily_dose_unit": "mg",
        "pediatric_dose": "6-11 years: 30 mg twice daily. >=12 years: Adult dose.",
        "pediatric_min_age": "6 years",
        "pediatric_max_daily_dose": "",
    },
    "37_claritine_10.txt": {
        "max_daily_dose": "10 mg/day",
        "max_daily_dose_value": 10,
        "max_daily_dose_unit": "mg",
        "pediatric_dose": "2-12 years: <30 kg: 5 mg once daily. >=30 kg: 10 mg once daily.",
        "pediatric_min_age": "2 years",
        "pediatric_max_daily_dose": "",
    },
    "38_otrivin_0_1.txt": {
        "max_daily_dose": "3 sprays/nostril/day",
        "max_daily_dose_value": 3,
        "max_daily_dose_unit": "sprays/nostril",
        "cross_selling": "Panadol Advance|Strepsils",
        "pediatric_dose": "0.05%: 2-11 years. 0.1%: >=12 years.",
        "pediatric_min_age": "2 years",
        "pediatric_max_daily_dose": "",
    },
    "39_ventolin_inhaler.txt": {
        "max_daily_dose": "8 puffs/day",
        "max_daily_dose_value": 8,
        "max_daily_dose_unit": "puffs",
        "cross_selling": "Singulair",
        "pediatric_dose": "Inhaler: 100-200 mcg as needed. Max according to physician.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "40_singulair_10.txt": {
        "max_daily_dose": "10 mg/day",
        "max_daily_dose_value": 10,
        "max_daily_dose_unit": "mg",
        "cross_selling": "Ventolin",
        "pediatric_dose": "6 months-5 years: 4 mg daily. 6-14 years: 5 mg daily. >=15 years: 10 mg daily.",
        "pediatric_min_age": "6 months",
        "pediatric_max_daily_dose": "",
    },
    "41_diflucan_150.txt": {
        "max_daily_dose": "400 mg/day",
        "max_daily_dose_value": 400,
        "max_daily_dose_unit": "mg",
        "cross_selling": "Lamisil",
        "pediatric_dose": "3-12 mg/kg/day depending on indication.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "42_lamisil_250.txt": {
        "max_daily_dose": "250 mg/day",
        "max_daily_dose_value": 250,
        "max_daily_dose_unit": "mg",
        "cross_selling": "Diflucan",
        "pediatric_dose": "Oral: Weight-based. Topical: Use according to product labeling.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "43_duphaston_10.txt": {
        "max_daily_dose": "30 mg/day",
        "max_daily_dose_value": 30,
        "max_daily_dose_unit": "mg",
        "cross_selling": "Folic Acid",
        "pediatric_dose": "Not indicated in pediatric patients.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "44_folic_acid_5.txt": {
        "max_daily_dose": "5 mg/day",
        "max_daily_dose_value": 5,
        "max_daily_dose_unit": "mg",
        "cross_selling": "Ferrotron",
        "pediatric_dose": "0.1-1 mg/day depending on indication.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "45_ferrotron.txt": {
        "max_daily_dose": "1 capsule/day",
        "max_daily_dose_value": 1,
        "max_daily_dose_unit": "capsule",
        "cross_selling": "Folic Acid",
        "pediatric_dose": "Dose depends on elemental iron requirement and age.",
        "pediatric_min_age": "",
        "pediatric_max_daily_dose": "",
    },
    "46_milga.txt": {
        "max_daily_dose": "3 tablets/day",
        "max_daily_dose_value": 3,
        "max_daily_dose_unit": "tablets",
        "cross_selling": "Jeparilon",
        "pediatric_dose": "Safety and efficacy in children not established.",
        "pediatric_min_age": "Not established",
        "pediatric_max_daily_dose": "",
    },
    "47_smecta.txt": {
        "max_daily_dose": "6 sachets/day",
        "max_daily_dose_value": 6,
        "max_daily_dose_unit": "sachets",
        "cross_selling": "Enterogermina",
        "pediatric_dose": "<1 year: 1 sachet/day. 1-2 years: 1-2 sachets/day. >2 years: 2-3 sachets/day.",
        "pediatric_min_age": "Infancy",
        "pediatric_max_daily_dose": "3 sachets/day",
    },
    "48_enterogermina.txt": {
        "max_daily_dose": "3 vials/day",
        "max_daily_dose_value": 3,
        "max_daily_dose_unit": "vials",
        "cross_selling": "Smecta",
        "pediatric_dose": "Infants/Children: 1-2 vials/day.",
        "pediatric_min_age": "Infancy",
        "pediatric_max_daily_dose": "2 vials/day",
    },
    "49_strepsils.txt": {
        "max_daily_dose": "12 lozenges/day",
        "max_daily_dose_value": 12,
        "max_daily_dose_unit": "lozenges",
        "cross_selling": "Panadol Advance|Otrivin",
        "pediatric_dose": "Not recommended under 6 years.",
        "pediatric_min_age": "6 years",
        "pediatric_max_daily_dose": "",
    },
    "50_comtrex.txt": {
        "max_daily_dose": "4 tablets/day",
        "max_daily_dose_value": 4,
        "max_daily_dose_unit": "tablets",
    },
    "51_panadol_extra.txt": {
        "cross_selling": "Strepsils|Otrivin",
    },
    "52_panadol_joint.txt": {
        "cross_selling": "Controloc 20",
    },
    "53_panadol_migraine.txt": {
        "cross_selling": "Otrivin|Strepsils",
    },
    "54_panadol_acute_head_cold.txt": {
        "max_daily_dose": "8 caplets/day",
        "max_daily_dose_value": 8,
        "max_daily_dose_unit": "caplets",
        "cross_selling": "Otrivin|Strepsils",
    },
    "55_panadol_cold_flu_all_in_one.txt": {
        "max_daily_dose": "8 capsules/day",
        "max_daily_dose_value": 8,
        "max_daily_dose_unit": "capsules",
    },
    "56_panadol_vapour_release.txt": {
        "max_daily_dose": "4 sachets/day",
        "max_daily_dose_value": 4,
        "max_daily_dose_unit": "sachets",
    },
}
