"""Generate 50 Egyptian commercial drug leaflets for RAG E2E corpus."""
from __future__ import annotations

from pathlib import Path

OUT = Path(r"d:\mini-rag\leaflets")

# Publicly typical Egyptian-market formulations for offline RAG testing.
# Not a substitute for the official MoH/PIL label.
DRUGS: list[dict] = [
    {
        "file": "01_panadol_paracetamol_500.txt",
        "title": "PANADOL Paracetamol 500 mg Film-Coated Tablets",
        "brand": "Panadol",
        "inn": "paracetamol",
        "form": "film-coated tablets",
        "strength": "500 mg",
        "company": "GlaxoSmithKline (Egypt market)",
        "uses": "Short-term relief of mild to moderate pain (headache, toothache, musculoskeletal pain) and fever.",
        "dose_adults": "1–2 tablets every 4–6 hours as needed. Do not exceed 8 tablets (4000 mg) in 24 hours. Leave at least 4 hours between doses.",
        "dose_children": "Not for children under 12 years unless an age-appropriate Panadol form is advised by a pharmacist/doctor.",
        "contra": [
            "Allergy to paracetamol or tablet excipients",
            "Severe liver disease",
            "Already taking other paracetamol-containing medicines",
        ],
        "warnings": "Overdose can cause serious liver damage. Seek urgent help if too much is taken, even if you feel well. Caution with chronic alcohol use or liver problems.",
        "interactions": "Prolonged regular high doses may affect warfarin INR. Do not combine with other paracetamol products. Tell your pharmacist about epilepsy or TB medicines that affect the liver.",
        "pregnancy": "May be used if clearly needed at the lowest effective dose for the shortest time.",
        "breastfeeding": "Compatible at recommended doses; only small amounts pass into breast milk.",
        "sides": "Rare at recommended doses: rash, allergic reaction. Overdose: liver injury.",
        "storage": "Store below 30°C in a dry place. Keep out of reach of children.",
        "supplements": "No routine supplement required. Avoid duplicating paracetamol in cold/flu multi-ingredient packs.",
    },
    {
        "file": "02_panadol_cold_flu_day.txt",
        "title": "PANADOL Cold & Flu Day Caplets",
        "brand": "Panadol Cold & Flu Day",
        "inn": "paracetamol + phenylephrine + caffeine (typical day formula)",
        "form": "caplets",
        "strength": "multi-ingredient day formula",
        "company": "GlaxoSmithKline (Egypt market)",
        "uses": "Daytime relief of cold and flu symptoms: headache, fever, blocked nose, and fatigue-related discomfort.",
        "dose_adults": "Adults and adolescents 12+: usually 2 caplets every 4–6 hours as needed. Do not exceed the labelled maximum daily dose. Do not use with other paracetamol products.",
        "dose_children": "Not for children under 12 years.",
        "contra": [
            "Allergy to any ingredient",
            "Severe hypertension or severe coronary disease (phenylephrine caution)",
            "Taking MAOIs or within 14 days of stopping MAOIs",
            "Severe liver disease",
        ],
        "warnings": "Contains a decongestant — avoid if you have uncontrolled high blood pressure, hyperthyroidism, or glaucoma unless advised. Do not drive if dizzy. Do not combine with other cold packs containing paracetamol.",
        "interactions": "Do not take with other paracetamol or phenylephrine products. Caution with antidepressants (MAOIs), blood pressure medicines, and digoxin. Caffeine adds stimulant effect.",
        "pregnancy": "Ask a doctor/pharmacist before use in pregnancy.",
        "breastfeeding": "Ask a pharmacist before use while breastfeeding.",
        "sides": "Nausea, insomnia, restlessness, raised blood pressure, palpitations, dry mouth.",
        "storage": "Store below 25–30°C as labelled. Keep dry.",
        "supplements": "Hydration and rest first. Do not stack multiple caffeine supplements.",
    },
    {
        "file": "03_panadol_sinus_relief_pe.txt",
        "title": "PANADOL Sinus Relief PE Caplets",
        "brand": "Panadol Sinus Relief PE",
        "inn": "paracetamol + phenylephrine",
        "form": "caplets",
        "strength": "sinus PE formula",
        "company": "GlaxoSmithKline (Egypt market)",
        "uses": "Relief of sinus pain/pressure with nasal congestion and fever/pain associated with sinusitis-like cold symptoms.",
        "dose_adults": "Adults and adolescents 12+: follow pack — commonly 2 caplets every 4–6 hours. Do not exceed labelled max. Max short-term OTC use unless advised.",
        "dose_children": "Not recommended under 12 years.",
        "contra": [
            "Paracetamol allergy",
            "Severe hypertension / severe heart disease",
            "MAOI therapy (or within 14 days)",
            "Severe hepatic impairment",
        ],
        "warnings": "Decongestant can raise blood pressure. Do not use with other paracetamol medicines. Stop if rash, facial swelling, or severe headache occurs.",
        "interactions": "MAOIs, other sympathomimetics, tricyclic antidepressants, beta-blockers — pharmacist check. Warfarin: prolonged paracetamol use may need INR review.",
        "pregnancy": "Seek advice before use.",
        "breastfeeding": "Seek advice before use.",
        "sides": "Nervousness, insomnia, nausea, palpitations, increased BP.",
        "storage": "Store in original blister below labelled temperature.",
        "supplements": "Saline nasal rinse may help congestion without duplicating PE.",
    },
    {
        "file": "04_cetal_cold_flu_day.txt",
        "title": "CETAL Cold & Flu Day Tablets",
        "brand": "Cetal Cold & Flu Day",
        "inn": "paracetamol + pseudoephedrine/phenylephrine-type day cold combination (local labelled actives)",
        "form": "tablets",
        "strength": "day cold & flu combination",
        "company": "Egyptian International Pharmaceutical Industries (typical Egypt SKU family)",
        "uses": "Daytime symptomatic relief of cold and flu: fever, headache, nasal congestion, and body aches.",
        "dose_adults": "Adults: as per pack leaflet (commonly 1–2 tablets every 6–8 hours). Do not exceed maximum daily paracetamol dose from all sources.",
        "dose_children": "Use only age-appropriate Cetal paediatric forms; this day cold pack is for adults/adolescents as labelled.",
        "contra": [
            "Allergy to ingredients",
            "Severe hypertension",
            "MAOI use",
            "Severe liver disease",
        ],
        "warnings": "Check every cold product for hidden paracetamol. Decongestant caution in heart disease and hyperthyroidism.",
        "interactions": "Other paracetamol products, MAOIs, blood-pressure medicines. Limit caffeine if formula contains stimulant components.",
        "pregnancy": "Ask pharmacist/doctor before use.",
        "breastfeeding": "Ask pharmacist/doctor before use.",
        "sides": "Insomnia, dry mouth, nausea, raised BP, rash (rare).",
        "storage": "Store below 30°C. Protect from moisture.",
        "supplements": "Prefer oral rehydration/fluids; avoid stacking another decongestant.",
    },
    {
        "file": "05_flurest_n.txt",
        "title": "FLUREST-N Tablets",
        "brand": "Flurest-N",
        "inn": "paracetamol + chlorpheniramine + pseudoephedrine (typical Egyptian Flurest-N composition)",
        "form": "tablets",
        "strength": "multi-ingredient cold formula",
        "company": "Egyptian market cold/flu brand (pharmacy OTC section)",
        "uses": "Relieves cold symptoms with runny/blocked nose, sneezing, fever, and aches. Antihistamine component may cause drowsiness.",
        "dose_adults": "Adults: usually 1 tablet 2–3 times daily as labelled. Do not exceed pack maximum. Avoid alcohol.",
        "dose_children": "Not for young children unless a paediatric label exists; ask pharmacist.",
        "contra": [
            "Allergy to any component",
            "Severe hypertension / severe CAD",
            "Narrow-angle glaucoma",
            "MAOI therapy",
            "Severe liver impairment",
        ],
        "warnings": "May cause drowsiness — do not drive. Do not combine with other paracetamol or sedating antihistamines.",
        "interactions": "Alcohol, sedatives, MAOIs, other decongestants, other paracetamol products.",
        "pregnancy": "Not preferred in pregnancy without clinician advice.",
        "breastfeeding": "Antihistamine/decongestant — ask pharmacist; may reduce milk or sedate infant.",
        "sides": "Drowsiness, dry mouth, constipation, insomnia/restlessness, urinary retention (rare).",
        "storage": "Store below 25–30°C in original pack.",
        "supplements": "Do not add another night/day cold combo.",
    },
    {
        "file": "06_congestal.txt",
        "title": "CONGESTAL Tablets",
        "brand": "Congestal",
        "inn": "paracetamol + chlorpheniramine + pseudoephedrine (typical Congestal formula)",
        "form": "tablets",
        "strength": "cold & congestion combination",
        "company": "Egyptian OTC cold brand (widely dispensed)",
        "uses": "Symptomatic treatment of nasal congestion, rhinorrhea, sneezing, fever, and headache associated with common cold.",
        "dose_adults": "Adults: commonly 1 tablet three times daily as labelled. Short-term use only.",
        "dose_children": "Paediatric use only if specifically labelled; otherwise avoid.",
        "contra": [
            "Hypersensitivity",
            "Severe hypertension",
            "MAOIs",
            "Severe hepatic disease",
            "Urinary retention / BPH caution with antihistamine",
        ],
        "warnings": "Sedation risk. Caution in asthma, glaucoma, prostate enlargement, diabetes, thyroid disease.",
        "interactions": "Alcohol, CNS depressants, other cold medicines, MAOIs, antihypertensives.",
        "pregnancy": "Avoid unless advised.",
        "breastfeeding": "Avoid or seek advice — antihistamine may affect infant.",
        "sides": "Drowsiness, dry mouth, blurred vision, nausea, palpitations.",
        "storage": "Keep dry below labelled temperature.",
        "supplements": "Saline spray preferred add-on rather than second oral decongestant.",
    },
    {
        "file": "07_sine_up.txt",
        "title": "SINE-UP Tablets",
        "brand": "Sine-Up",
        "inn": "paracetamol + pseudoephedrine + chlorpheniramine (typical Sine-Up formula)",
        "form": "tablets",
        "strength": "sinus/cold combination",
        "company": "Egyptian pharmacy cold/sinus brand",
        "uses": "Sinus congestion, pressure headache, runny nose, and feverish cold symptoms.",
        "dose_adults": "Adults: as labelled, often 1 tablet 2–3 times daily. Do not exceed paracetamol daily limits.",
        "dose_children": "Not for children unless paediatric SKU advised.",
        "contra": [
            "Allergy",
            "Severe hypertension",
            "MAOI use",
            "Severe liver disease",
        ],
        "warnings": "May cause drowsiness or insomnia depending on response. Monitor blood pressure if hypertensive.",
        "interactions": "Other decongestants, sedatives, alcohol, other paracetamol products.",
        "pregnancy": "Ask clinician before use.",
        "breastfeeding": "Ask clinician before use.",
        "sides": "Dry mouth, sleep disturbance, drowsiness, nausea.",
        "storage": "Store in original strip; protect from humidity.",
        "supplements": "Avoid combining with Congestal/Flurest-type duplicates.",
    },
    {
        "file": "08_bradozen.txt",
        "title": "BRADOZEN Lozenges / Oral Antiseptic",
        "brand": "Bradozen",
        "inn": "local antiseptic/anaesthetic throat lozenge actives (branded Egyptian sore-throat SKU)",
        "form": "lozenges",
        "strength": "as labelled per lozenge",
        "company": "Egyptian OTC sore-throat brand",
        "uses": "Local symptomatic relief of sore throat, mouth irritation, and mild pharyngitis discomfort.",
        "dose_adults": "Dissolve 1 lozenge slowly every 2–3 hours as needed. Do not exceed labelled daily maximum.",
        "dose_children": "Only if age threshold on pack is met; choking risk in young children.",
        "contra": [
            "Allergy to any lozenge component",
            "Severe oral mucosal disease needing medical care",
        ],
        "warnings": "If sore throat persists >3 days, is severe, or comes with high fever/rash, seek medical care. Not a systemic antibiotic.",
        "interactions": "Minimal systemic interactions; space from other oral gels if needed.",
        "pregnancy": "Generally acceptable locally if needed; confirm pack advice.",
        "breastfeeding": "Usually acceptable; confirm pack advice.",
        "sides": "Local numbness, taste change, irritation (uncommon).",
        "storage": "Store sealed; protect from heat/moisture.",
        "supplements": "Warm fluids/honey (age-appropriate) as supportive care.",
    },
    {
        "file": "09_notussil.txt",
        "title": "NOTUSSIL Syrup",
        "brand": "Notussil",
        "inn": "cough suppressant / expectorant combination as per local Notussil label",
        "form": "syrup",
        "strength": "as labelled per 5 mL",
        "company": "Egyptian cough syrup brand",
        "uses": "Symptomatic relief of dry or irritating cough associated with upper respiratory infections (per label indication).",
        "dose_adults": "Adults: typically 5–10 mL two to three times daily as labelled.",
        "dose_children": "Dose by age band on pack only. Do not use in very young children unless explicitly labelled.",
        "contra": [
            "Allergy to ingredients",
            "Cough with excessive purulent sputum needing medical review",
            "MAOI caution if opioid-type antitussive present on label",
        ],
        "warnings": "Do not use cough suppressants for productive cough that should be cleared unless advised. Sedation possible.",
        "interactions": "Alcohol, sedatives, other cough/cold combos — avoid stacking.",
        "pregnancy": "Ask doctor/pharmacist.",
        "breastfeeding": "Ask doctor/pharmacist.",
        "sides": "Drowsiness, nausea, constipation (if opioid antitussive), allergy (rare).",
        "storage": "Store upright below labelled temperature. Shake if instructed.",
        "supplements": "Humidified air and fluids; honey for children >1 year if appropriate.",
    },
    {
        "file": "10_tussigreen.txt",
        "title": "TUSSIGREEN Syrup",
        "brand": "Tussigreen",
        "inn": "herbal/expectorant cough syrup actives as labelled (Egyptian Tussigreen SKU)",
        "form": "syrup",
        "strength": "as labelled per 5 mL",
        "company": "Egyptian herbal cough brand",
        "uses": "Supportive relief of cough and throat irritation; often used as an expectorant/soothing cough syrup.",
        "dose_adults": "Adults: as labelled (commonly 5–10 mL 2–3 times daily).",
        "dose_children": "Follow age dosing table on bottle; do not exceed.",
        "contra": [
            "Allergy to plant/herbal components",
            "Fructose intolerance if sugar alcohols/sugars contraindicated on label",
        ],
        "warnings": "If cough lasts >1 week, or hemoptysis/fever persists, seek care. Check sugar content in diabetics.",
        "interactions": "Usually low; still avoid duplicating sedating cough medicines.",
        "pregnancy": "Confirm with pharmacist — herbal products vary.",
        "breastfeeding": "Confirm with pharmacist.",
        "sides": "GI upset, allergy, diarrhoea (uncommon).",
        "storage": "Keep tightly closed; refrigerate only if label says so.",
        "supplements": "Hydration; do not combine with codeine cough syrups unless advised.",
    },
    {
        "file": "11_daflon_500.txt",
        "title": "DAFLON 500 mg Film-Coated Tablets",
        "brand": "Daflon 500",
        "inn": "micronized purified flavonoid fraction (diosmin 450 mg + hesperidin 50 mg)",
        "form": "film-coated tablets",
        "strength": "500 mg",
        "company": "Servier (widely dispensed in Egypt)",
        "uses": "Venous circulation disorders (heavy legs, pain, oedema) and acute hemorrhoidal attacks as labelled.",
        "dose_adults": "Chronic venous disease: often 2 tablets daily with meals. Acute hemorrhoids: higher short course as labelled (e.g. 6/day then taper) — follow pack/doctor.",
        "dose_children": "Not typically used in children.",
        "contra": ["Hypersensitivity to diosmin/hesperidin or excipients"],
        "warnings": "If hemorrhoidal symptoms persist after short treatment, proctologic examination is needed. Not a substitute for vein hygiene measures (walking, elevation, compression when advised).",
        "interactions": "No major routine CYP interactions; tell pharmacist about all medicines.",
        "pregnancy": "Use only if needed and advised.",
        "breastfeeding": "Avoid unless advised — limited data.",
        "sides": "Dyspepsia, diarrhoea, nausea, rash (uncommon).",
        "storage": "Store below 30°C.",
        "supplements": "Leg elevation and mobility advice; ask before adding other vein herbals.",
    },
    {
        "file": "12_daflon_1000.txt",
        "title": "DAFLON 1000 mg Film-Coated Tablets",
        "brand": "Daflon 1000",
        "inn": "micronized purified flavonoid fraction (diosmin/hesperidin 1000 mg)",
        "form": "film-coated tablets",
        "strength": "1000 mg",
        "company": "Servier (Egypt market)",
        "uses": "Same venotonic indications as Daflon 500 with once/twice daily convenience dosing per label.",
        "dose_adults": "Often 1 tablet daily (or as prescribed) with food. Hemorrhoidal flares: follow higher short-term labelled schedule.",
        "dose_children": "Not indicated.",
        "contra": ["Allergy to flavonoids/excipients"],
        "warnings": "Persistent rectal bleeding needs medical assessment.",
        "interactions": "Minimal known clinically significant interactions.",
        "pregnancy": "Only if prescribed.",
        "breastfeeding": "Not preferred.",
        "sides": "GI discomfort, headache (uncommon).",
        "storage": "Below 30°C in original blister.",
        "supplements": "Do not duplicate with multiple diosmin brands.",
    },
    {
        "file": "13_controloc_20.txt",
        "title": "CONTROLOC 20 mg Gastro-Resistant Tablets",
        "brand": "Controloc 20",
        "inn": "pantoprazole",
        "form": "gastro-resistant tablets",
        "strength": "20 mg",
        "company": "Abbott/Takeda lineage brand (Egypt retail)",
        "uses": "Acid-related disorders: GERD/heartburn, peptic ulcer treatment/prevention pathways as prescribed; PPI class.",
        "dose_adults": "Often 20 mg once daily before breakfast for symptomatic GERD, or as prescribed. Swallow whole — do not crush.",
        "dose_children": "Specialist dosing only.",
        "contra": [
            "Allergy to pantoprazole or other PPIs",
            "Concomitant use with rilpivirine-containing products where contraindicated",
        ],
        "warnings": "Long-term use: discuss magnesium, B12, bone risk. Exclude malignancy if alarm symptoms (weight loss, bleeding, dysphagia).",
        "interactions": "May affect absorption of ketoconazole/itraconazole/iron/some antivirals. Methotrexate high-dose caution. Warfarin: monitor if clinically indicated.",
        "pregnancy": "Only if clearly needed.",
        "breastfeeding": "Excreted in milk — decide with clinician.",
        "sides": "Headache, diarrhoea, abdominal pain, nausea; rare hypomagnesemia with prolonged use.",
        "storage": "Store below 25–30°C. Keep dry.",
        "supplements": "Calcium citrate may be preferred over carbonate on long-term PPI; check magnesium/B12 if prolonged therapy.",
    },
    {
        "file": "14_jeparilon.txt",
        "title": "JEPARILON Soft Gelatin Capsules / Gastro Pack",
        "brand": "Jeparilon",
        "inn": "rebamipide or gastroprotective combination as per local Jeparilon label",
        "form": "capsules",
        "strength": "as labelled",
        "company": "Egyptian gastro pharmacy brand",
        "uses": "Supportive treatment of gastritis/gastric mucosal protection and dyspepsia as indicated on the Egyptian label.",
        "dose_adults": "Adults: commonly 1 capsule two to three times daily after meals as prescribed/labelled.",
        "dose_children": "Not routinely used unless prescribed.",
        "contra": ["Known hypersensitivity to the active or excipients"],
        "warnings": "Not a replacement for H. pylori eradication regimens when indicated. Seek care for black stools or vomiting blood.",
        "interactions": "Generally limited; still separate from some antacids if label advises.",
        "pregnancy": "Use only if prescribed.",
        "breastfeeding": "Use only if prescribed.",
        "sides": "Constipation, diarrhoea, rash (uncommon).",
        "storage": "Store in a cool dry place.",
        "supplements": "Avoid NSAID self-medication that worsens gastritis.",
    },
    {
        "file": "15_anaseziago.txt",
        "title": "ANASEZIAGO Tablets",
        "brand": "Anaseziago",
        "inn": "thiocolchicoside or muscle-relaxant component as per local Anaseziago presentation",
        "form": "tablets",
        "strength": "as labelled",
        "company": "Egyptian musculoskeletal brand",
        "uses": "Adjunctive relief of painful muscle contractures / acute low-back muscle spasm as prescribed.",
        "dose_adults": "Adults: follow prescription — often short courses only. Do not exceed labelled duration.",
        "dose_children": "Contraindicated/avoid in younger ages if thiocolchicoside — follow strict label.",
        "contra": [
            "Pregnancy",
            "Breastfeeding",
            "Hypersensitivity",
            "Age restrictions per thiocolchicoside safety communications",
        ],
        "warnings": "Regulatory limits exist for thiocolchicoside systemic use (genotoxicity concerns) — short-term only as directed. May cause drowsiness.",
        "interactions": "Alcohol and sedatives increase CNS depression.",
        "pregnancy": "Do not use.",
        "breastfeeding": "Do not use.",
        "sides": "Drowsiness, diarrhoea, allergy; rare seizures reported with muscle relaxants — stop if occur.",
        "storage": "Below 25–30°C.",
        "supplements": "Physiotherapy/rest as advised; do not combine multiple muscle relaxants.",
    },
    {
        "file": "16_adol_500.txt",
        "title": "ADOL Paracetamol 500 mg Caplets",
        "brand": "Adol",
        "inn": "paracetamol",
        "form": "caplets",
        "strength": "500 mg",
        "company": "Julphar / regional brand widely sold in Egypt",
        "uses": "Pain and fever reduction.",
        "dose_adults": "1–2 caplets every 4–6 hours. Max 4 g paracetamol/day from all sources.",
        "dose_children": "Use paediatric Adol syrup/drops by weight.",
        "contra": ["Paracetamol allergy", "Severe hepatic impairment"],
        "warnings": "Overdose risk — liver failure. Check combination cold products.",
        "interactions": "Warfarin with prolonged regular use; enzyme-inducing antiepileptics — pharmacist check.",
        "pregnancy": "OK if needed, lowest dose/shortest time.",
        "breastfeeding": "Compatible at standard doses.",
        "sides": "Rare rash; overdose hepatotoxicity.",
        "storage": "Dry place below 30°C.",
        "supplements": "Do not duplicate with Panadol/Cetal same day carelessly.",
    },
    {
        "file": "17_cataflam_25.txt",
        "title": "CATAFLAM Diclofenac Potassium 25/50 mg Tablets",
        "brand": "Cataflam",
        "inn": "diclofenac potassium",
        "form": "tablets",
        "strength": "25–50 mg",
        "company": "Novartis (Egypt market)",
        "uses": "Acute pain and inflammation (dental pain, post-traumatic pain, dysmenorrhea, acute musculoskeletal pain).",
        "dose_adults": "Usually 50 mg two to three times daily. Max typically 150 mg/day. Take with food if stomach upset.",
        "dose_children": "Specialist/paediatric dosing only.",
        "contra": [
            "Active peptic ulcer / GI bleeding",
            "NSAID allergy / aspirin-exacerbated asthma",
            "Severe heart failure",
            "Third trimester pregnancy",
            "Severe hepatic or renal failure",
        ],
        "warnings": "CV and GI risks increase with dose/duration. Avoid in late pregnancy.",
        "interactions": "Warfarin/anticoagulants, SSRIs, ACEI/ARB + diuretic (renal), methotrexate, lithium, other NSAIDs.",
        "pregnancy": "Avoid in third trimester; earlier only if prescribed.",
        "breastfeeding": "Small amounts in milk — short courses may be acceptable; prefer alternatives when possible.",
        "sides": "Dyspepsia, nausea, headache; serious: GI bleed, oedema, rash.",
        "storage": "Below 25–30°C; protect from moisture.",
        "supplements": "Avoid high-dose fish oil stacking for bleed risk; take with food.",
    },
    {
        "file": "18_brufen_400.txt",
        "title": "BRUFEN Ibuprofen 400 mg Tablets",
        "brand": "Brufen",
        "inn": "ibuprofen",
        "form": "tablets",
        "strength": "400 mg",
        "company": "Abbott (Egypt market)",
        "uses": "Pain, inflammation, fever, dysmenorrhea, musculoskeletal pain.",
        "dose_adults": "200–400 mg every 6–8 hours after food. OTC self-care usually ≤1200 mg/day unless prescribed higher.",
        "dose_children": "Use paediatric ibuprofen syrup by weight; 400 mg tablets not for young children.",
        "contra": [
            "NSAID allergy",
            "Active ulcer/GI bleed",
            "Third trimester",
            "Severe heart/liver/kidney failure",
        ],
        "warnings": "Can worsen asthma in sensitive patients. Lowest dose/shortest time.",
        "interactions": "Warfarin, aspirin (antiplatelet timing), SSRIs, antihypertensives, other NSAIDs.",
        "pregnancy": "Avoid in third trimester.",
        "breastfeeding": "Usually compatible short-term at standard doses.",
        "sides": "Stomach pain, heartburn, nausea; rare bleed/allergy.",
        "storage": "Dry place below 25°C.",
        "supplements": "Prefer paracetamol on warfarin instead of Brufen.",
    },
    {
        "file": "19_antinal.txt",
        "title": "ANTINAL Nifuroxazide 200 mg Capsules",
        "brand": "Antinal",
        "inn": "nifuroxazide",
        "form": "capsules",
        "strength": "200 mg",
        "company": "Egyptian market antidiarrheal (widely known brand)",
        "uses": "Acute diarrhoea of presumed infectious origin without invasive signs, as labelled.",
        "dose_adults": "Adults: commonly 200 mg four times daily for up to 3–7 days as labelled/prescribed.",
        "dose_children": "Suspension form preferred; dose by age/weight.",
        "contra": ["Allergy to nitrofuran derivatives", "Invasive diarrhoea with high fever/bloody stools needing different care"],
        "warnings": "Rehydration is essential. Seek care if blood in stool, high fever, or dehydration.",
        "interactions": "Alcohol may cause intolerance reactions with some nitrofurans — avoid alcohol.",
        "pregnancy": "Ask clinician.",
        "breastfeeding": "Ask clinician.",
        "sides": "Rash, abdominal discomfort, allergy (rare).",
        "storage": "Below 25–30°C.",
        "supplements": "ORS (oral rehydration salts) are first-line supportive care; probiotics optional separated in time.",
    },
    {
        "file": "20_flagyl_500.txt",
        "title": "FLAGYL Metronidazole 500 mg Tablets",
        "brand": "Flagyl",
        "inn": "metronidazole",
        "form": "tablets",
        "strength": "500 mg",
        "company": "Sanofi (Egypt market)",
        "uses": "Anaerobic bacterial infections, amoebiasis, giardiasis, bacterial vaginosis, and other labelled indications.",
        "dose_adults": "Depends on indication — often 500 mg two to three times daily. Complete the full course.",
        "dose_children": "Weight-based; use appropriate strength/form.",
        "contra": ["Allergy to metronidazole", "First trimester for some indications — follow obstetric advice", "Alcohol during/after course"],
        "warnings": "STRICT alcohol avoidance during treatment and ≥48 hours after (disulfiram-like reaction). May darken urine.",
        "interactions": "Warfarin (INR↑), lithium, phenytoin, alcohol, disulfiram.",
        "pregnancy": "Indication-specific; clinician decision.",
        "breastfeeding": "Single doses sometimes used; prolonged courses — discuss pumping/timing.",
        "sides": "Metallic taste, nausea, abdominal pain; rare neuropathy with prolonged use.",
        "storage": "Protect from light/moisture.",
        "supplements": "Take with food if nausea; no alcohol-containing tonics.",
    },
    {
        "file": "21_augmentin_1g.txt",
        "title": "AUGMENTIN 1 g Amoxicillin/Clavulanate Tablets",
        "brand": "Augmentin",
        "inn": "amoxicillin + clavulanic acid",
        "form": "film-coated tablets",
        "strength": "875/125 mg or 1000 mg local SKU as labelled",
        "company": "GSK (Egypt market)",
        "uses": "Bacterial infections of ENT, respiratory tract, skin, urinary tract when susceptible organisms suspected.",
        "dose_adults": "Often 1 tablet twice daily every 12 hours with meals. Course usually 5–7+ days as prescribed.",
        "dose_children": "Use paediatric suspension; do not split adult logic carelessly.",
        "contra": [
            "Penicillin/amoxicillin allergy",
            "History of Augmentin-associated jaundice/hepatic dysfunction",
            "Mononucleosis caution (rash)",
        ],
        "warnings": "Diarrhoea common; report severe colitis symptoms. Dose adjust in renal impairment.",
        "interactions": "Warfarin (monitor INR), methotrexate, probenecid, allopurinol (rash), oral contraceptives counselling.",
        "pregnancy": "Widely used when indicated.",
        "breastfeeding": "Generally compatible; watch infant for diarrhoea/thrush.",
        "sides": "Diarrhoea, nausea, rash, thrush; rare hepatitis.",
        "storage": "Dry place; suspensions often refrigerated after reconstitution — check label.",
        "supplements": "Probiotic ≥2 hours away from dose may help antibiotic-associated diarrhoea.",
    },
    {
        "file": "22_hibiotic_1g.txt",
        "title": "HI-BIOTIC 1 g Amoxicillin/Clavulanate",
        "brand": "Hi-Biotic",
        "inn": "amoxicillin + clavulanic acid",
        "form": "tablets",
        "strength": "1000 mg",
        "company": "Egyptian brand alternative to Augmentin-class",
        "uses": "Same class indications as amoxicillin/clavulanate for bacterial infections as prescribed.",
        "dose_adults": "Typically 1 tablet every 12 hours with food, or as prescribed.",
        "dose_children": "Paediatric forms only.",
        "contra": ["Beta-lactam allergy", "Prior cholestatic jaundice with amox/clav"],
        "warnings": "Complete course. Hydration; report severe diarrhoea.",
        "interactions": "Similar to Augmentin: warfarin, methotrexate, allopurinol, contraceptives counselling.",
        "pregnancy": "If prescribed.",
        "breastfeeding": "Usually compatible.",
        "sides": "GI upset, rash, candida.",
        "storage": "Below 25–30°C dry.",
        "supplements": "Probiotic separated by 2 hours.",
    },
    {
        "file": "23_zithrokan_500.txt",
        "title": "ZITHROKAN Azithromycin 500 mg",
        "brand": "Zithrokan",
        "inn": "azithromycin",
        "form": "capsules/tablets",
        "strength": "500 mg",
        "company": "Egyptian azithromycin brand",
        "uses": "Respiratory tract infections, skin infections, some STIs and other labelled susceptible infections.",
        "dose_adults": "Commonly 500 mg once daily for 3 days, or 500 mg day 1 then 250 mg days 2–5 — follow prescription.",
        "dose_children": "Mg/kg suspension regimens.",
        "contra": ["Allergy to macrolides", "History of cholestatic jaundice with azithromycin"],
        "warnings": "QT prolongation risk — caution with arrhythmia history. Complete course.",
        "interactions": "Antacids (space 2 hours), warfarin, digoxin, other QT-prolonging drugs, some statins (myopathy risk with macrolides — azithromycin lower than clarithromycin but still review).",
        "pregnancy": "If clearly needed.",
        "breastfeeding": "Usually compatible; watch infant GI.",
        "sides": "Nausea, diarrhoea, abdominal pain; rare hepatotoxicity/QT effects.",
        "storage": "Dry room temperature.",
        "supplements": "Space aluminium/magnesium antacids from dose.",
    },
    {
        "file": "24_ciprobay_500.txt",
        "title": "CIPROBAY Ciprofloxacin 500 mg Tablets",
        "brand": "Ciprobay",
        "inn": "ciprofloxacin",
        "form": "film-coated tablets",
        "strength": "500 mg",
        "company": "Bayer (Egypt market)",
        "uses": "Gram-negative and other susceptible infections (UTI, GI, bone/joint, etc.) as prescribed — not for trivial viral colds.",
        "dose_adults": "Often 500 mg every 12 hours for duration prescribed. Drink fluids.",
        "dose_children": "Generally avoided unless specialist exception (cartilage risk).",
        "contra": [
            "Allergy to fluoroquinolones",
            "Concomitant tizanidine",
            "Pregnancy/breastfeeding generally avoid",
        ],
        "warnings": "Tendinitis/tendon rupture risk, CNS effects, QT risk, photosensitivity. Stop if tendon pain.",
        "interactions": "Dairy/antacids/iron/calcium reduce absorption — separate 2–4 hours. Warfarin, theophylline, QT drugs.",
        "pregnancy": "Avoid.",
        "breastfeeding": "Avoid.",
        "sides": "Nausea, diarrhoea, dizziness, insomnia; serious tendon/CNS reactions.",
        "storage": "Protect from moisture/light.",
        "supplements": "Do NOT take with milk/calcium/iron at the same time.",
    },
    {
        "file": "25_risek_20.txt",
        "title": "RISEK Omeprazole 20 mg Capsules",
        "brand": "Risek",
        "inn": "omeprazole",
        "form": "gastro-resistant capsules",
        "strength": "20 mg",
        "company": "Egyptian PPI brand (omeprazole)",
        "uses": "GERD, peptic ulcer, NSAID ulcer risk reduction pathways, H. pylori regimens as part of combination therapy.",
        "dose_adults": "20 mg once daily before breakfast, or as prescribed. Swallow whole.",
        "dose_children": "Specialist dosing.",
        "contra": ["Omeprazole/PPI allergy"],
        "warnings": "Long-term monitoring considerations (Mg, B12). Alarm symptoms need investigation.",
        "interactions": "Clopidogrel concern with omeprazole — discuss alternative acid suppression if dual therapy critical. Iron/calcium absorption; methotrexate; some antivirals.",
        "pregnancy": "If needed under advice.",
        "breastfeeding": "Discuss — small amounts in milk.",
        "sides": "Headache, diarrhoea, abdominal pain.",
        "storage": "Dry place below 25–30°C.",
        "supplements": "Calcium citrate preference on long-term PPI; review magnesium.",
    },
    {
        "file": "26_gaviscon.txt",
        "title": "GAVISCON Oral Suspension / Tablets",
        "brand": "Gaviscon",
        "inn": "sodium alginate + antacid system (sodium bicarbonate / calcium carbonate variants)",
        "form": "suspension or chewable tablets",
        "strength": "as labelled",
        "company": "Reckitt (Egypt market)",
        "uses": "Heartburn, acid regurgitation, indigestion by forming a raft over stomach contents.",
        "dose_adults": "After meals and at bedtime — typically 10–20 mL suspension or 2 tablets chewed as labelled.",
        "dose_children": "Age-specific paediatric Gaviscon products only.",
        "contra": ["Severe renal impairment caution with ion content", "Allergy to ingredients"],
        "warnings": "High sodium in some formulations — caution in hypertension/heart failure. Separate from some medicines by 2 hours.",
        "interactions": "Can reduce absorption of some antibiotics/iron/thyroxine — space doses.",
        "pregnancy": "Often used for pregnancy heartburn when advised.",
        "breastfeeding": "Generally acceptable.",
        "sides": "Constipation or diarrhoea depending on salts; bloating.",
        "storage": "Shake suspension; do not freeze.",
        "supplements": "Elevate head of bed; avoid late heavy meals.",
    },
    {
        "file": "27_motilium_10.txt",
        "title": "MOTILIUM Domperidone 10 mg Tablets",
        "brand": "Motilium",
        "inn": "domperidone",
        "form": "tablets",
        "strength": "10 mg",
        "company": "Janssen (Egypt market)",
        "uses": "Nausea and vomiting; dyspepsia motility symptoms as labelled. Restricted duration/dose due to cardiac risk.",
        "dose_adults": "Often 10 mg up to three times daily before meals. Use lowest dose/shortest time (often ≤7 days).",
        "dose_children": "Restricted; specialist only.",
        "contra": [
            "Prolactinoma",
            "QT prolongation / significant cardiac disease",
            "Strong CYP3A4 inhibitors",
            "Moderate-severe hepatic impairment",
        ],
        "warnings": "Cardiac arrhythmia risk — avoid if QT risk factors. Not for routine milk stimulation without specialist oversight.",
        "interactions": "Ketoconazole, erythromycin, other QT drugs, strong CYP3A4 inhibitors — contraindicated combinations exist.",
        "pregnancy": "Only if benefit outweighs risk.",
        "breastfeeding": "Passes into milk — clinician decision.",
        "sides": "Dry mouth, headache, diarrhoea; rare extrapyramidal symptoms; cardiac events (rare).",
        "storage": "Below 30°C.",
        "supplements": "ORS if vomiting causes dehydration; ECG review if cardiac history.",
    },
    {
        "file": "28_buscopan.txt",
        "title": "BUSCOPAN Hyoscine Butylbromide 10 mg Tablets",
        "brand": "Buscopan",
        "inn": "hyoscine butylbromide",
        "form": "tablets",
        "strength": "10 mg",
        "company": "Boehringer Ingelheim (Egypt)",
        "uses": "Abdominal cramps, intestinal/biliary colic, IBS-related spasm.",
        "dose_adults": "1–2 tablets 3–4 times daily as labelled/prescribed.",
        "dose_children": "Age-limited; ask pharmacist.",
        "contra": [
            "Myasthenia gravis",
            "Megacolon",
            "Narrow-angle glaucoma",
            "Mechanical stenosis / paralytic ileus",
        ],
        "warnings": "Anticholinergic effects — caution in prostatic hypertrophy and tachycardia.",
        "interactions": "Other anticholinergics, TCAs, antihistamines — additive dry mouth/retention.",
        "pregnancy": "Ask clinician.",
        "breastfeeding": "Ask clinician.",
        "sides": "Dry mouth, constipation, blurred vision, tachycardia, urinary retention.",
        "storage": "Dry room temperature.",
        "supplements": "Heat pack/hydration for mild cramps if appropriate.",
    },
    {
        "file": "29_concor_5.txt",
        "title": "CONCOR Bisoprolol 5 mg Film-Coated Tablets",
        "brand": "Concor",
        "inn": "bisoprolol fumarate",
        "form": "film-coated tablets",
        "strength": "5 mg",
        "company": "Merck (Egypt market)",
        "uses": "Hypertension, chronic stable angina, stable chronic heart failure (as part of GDMT when indicated).",
        "dose_adults": "Individualized — often 2.5–5 mg once daily, titrated. Do not stop abruptly.",
        "dose_children": "Not routinely used.",
        "contra": [
            "Acute decompensated heart failure",
            "Severe bradycardia / AV block (relevant degrees)",
            "Severe asthma/COPD caution (beta-blockers)",
            "Cardiogenic shock",
        ],
        "warnings": "Do not discontinue suddenly. Monitor HR/BP. Caution in diabetics (may mask hypoglycemia).",
        "interactions": "Verapamil/diltiazem, other rate-limiting drugs, clonidine withdrawal caution, digoxin, insulin/sulfonylureas (masking).",
        "pregnancy": "Specialist decision only.",
        "breastfeeding": "Specialist decision.",
        "sides": "Bradycardia, fatigue, cold extremities, dizziness, sleep disturbance.",
        "storage": "Below 25–30°C.",
        "supplements": "Do not self-add OTC decongestants that raise BP/HR without advice.",
    },
    {
        "file": "30_norvasc_5.txt",
        "title": "NORVASC Amlodipine 5 mg Tablets",
        "brand": "Norvasc",
        "inn": "amlodipine besylate",
        "form": "tablets",
        "strength": "5 mg",
        "company": "Pfizer (Egypt market)",
        "uses": "Hypertension and chronic stable angina.",
        "dose_adults": "Usually 5 mg once daily; may increase to 10 mg if needed.",
        "dose_children": "Specialist paediatric hypertension dosing.",
        "contra": ["Severe hypotension", "Allergy to dihydropyridines", "Shock"],
        "warnings": "Ankle oedema common. Caution in severe aortic stenosis / heart failure as clinically relevant.",
        "interactions": "Strong CYP3A4 inhibitors may raise levels; grapefruit large amounts; simvastatin dose limits with amlodipine.",
        "pregnancy": "Only if necessary.",
        "breastfeeding": "Discuss — excreted in milk.",
        "sides": "Ankle swelling, flushing, headache, palpitations, fatigue.",
        "storage": "Dry place.",
        "supplements": "Limit excessive grapefruit; sodium-controlled diet advice.",
    },
    {
        "file": "31_glucophage_500.txt",
        "title": "GLUCOPHAGE Metformin 500 mg Tablets",
        "brand": "Glucophage",
        "inn": "metformin hydrochloride",
        "form": "tablets",
        "strength": "500 mg",
        "company": "Merck (Egypt market)",
        "uses": "Type 2 diabetes mellitus with diet/exercise.",
        "dose_adults": "Start low (e.g. 500 mg once/twice daily with meals) and titrate. Max per label/prescription.",
        "dose_children": "Specialist only from approved ages.",
        "contra": [
            "Severe renal impairment (eGFR cut-offs)",
            "Acute metabolic acidosis",
            "Acute conditions with hypoxia/dehydration risk as listed",
        ],
        "warnings": "Hold around iodinated contrast per protocol. Alcohol binges raise lactic acidosis risk. Long-term B12 monitoring.",
        "interactions": "Alcohol, iodinated contrast, cimetidine, drugs affecting renal function.",
        "pregnancy": "Specialist diabetes care — insulin often preferred.",
        "breastfeeding": "Usually compatible; clinician confirm.",
        "sides": "Diarrhoea, nausea, abdominal discomfort; rare lactic acidosis.",
        "storage": "Below 25–30°C.",
        "supplements": "Check vitamin B12 periodically on long-term therapy.",
    },
    {
        "file": "32_amaryl_2.txt",
        "title": "AMARYL Glimepiride 2 mg Tablets",
        "brand": "Amaryl",
        "inn": "glimepiride",
        "form": "tablets",
        "strength": "2 mg",
        "company": "Sanofi (Egypt)",
        "uses": "Type 2 diabetes as sulfonylurea add-on/alternative when appropriate.",
        "dose_adults": "Usually once daily with breakfast. Titrate carefully to avoid hypoglycemia.",
        "dose_children": "Not indicated.",
        "contra": ["Type 1 diabetes", "DKA", "Severe renal/hepatic disease as labelled", "Sulfonylurea allergy"],
        "warnings": "Hypoglycemia risk — educate on symptoms. Caution in elderly.",
        "interactions": "Alcohol, other antidiabetics, azoles, sulfonamides, beta-blockers (masking), warfarin (rare).",
        "pregnancy": "Not preferred — specialist.",
        "breastfeeding": "Avoid.",
        "sides": "Hypoglycemia, weight gain, rash, GI upset.",
        "storage": "Dry room temperature.",
        "supplements": "Carry glucose source; consistent meal timing.",
    },
    {
        "file": "33_lipitor_20.txt",
        "title": "LIPITOR Atorvastatin 20 mg Tablets",
        "brand": "Lipitor",
        "inn": "atorvastatin",
        "form": "tablets",
        "strength": "20 mg",
        "company": "Pfizer (Egypt)",
        "uses": "Hypercholesterolemia and cardiovascular risk reduction.",
        "dose_adults": "10–20 mg once daily commonly; adjust per lipids/risk. Same time daily.",
        "dose_children": "Specialist familial hypercholesterolemia regimens.",
        "contra": ["Active liver disease", "Pregnancy", "Breastfeeding", "Allergy"],
        "warnings": "Report unexplained muscle pain/dark urine. Liver enzymes may be monitored. Avoid large grapefruit intake.",
        "interactions": "Clarithromycin/azole antifungals, gemfibrozil, cyclosporine, warfarin (monitor), amlodipine (dose awareness).",
        "pregnancy": "Contraindicated.",
        "breastfeeding": "Contraindicated.",
        "sides": "Myalgia, headache, GI upset; rare rhabdomyolysis/hepatitis.",
        "storage": "Below 25°C.",
        "supplements": "Avoid red yeast rice. Correct vitamin D deficiency if present; CoQ10 optional only after review.",
    },
    {
        "file": "34_plavix_75.txt",
        "title": "PLAVIX Clopidogrel 75 mg Tablets",
        "brand": "Plavix",
        "inn": "clopidogrel",
        "form": "film-coated tablets",
        "strength": "75 mg",
        "company": "Sanofi (Egypt)",
        "uses": "Antiplatelet prevention after ACS/stent or other atherothrombotic indications as prescribed.",
        "dose_adults": "Maintenance usually 75 mg once daily. Loading doses are clinician-directed.",
        "dose_children": "Not routine.",
        "contra": ["Active pathological bleeding", "Severe liver impairment", "Allergy"],
        "warnings": "Bleeding risk. Do not stop suddenly after stenting without cardiologist advice.",
        "interactions": "Omeprazole/esomeprazole may reduce activation — discuss PPI choice. Warfarin/NSAIDs/SSRIs increase bleed risk. Opioids may delay absorption in ACS settings.",
        "pregnancy": "Only if clearly needed.",
        "breastfeeding": "Not recommended.",
        "sides": "Bruising, bleeding, dyspepsia, rare TTP.",
        "storage": "Dry place.",
        "supplements": "Avoid ginkgo/high-dose fish oil/garlic tablets unless approved.",
    },
    {
        "file": "35_aspocid_75.txt",
        "title": "ASPOCID Low-Dose Aspirin 75 mg",
        "brand": "Aspocid",
        "inn": "acetylsalicylic acid (aspirin)",
        "form": "tablets",
        "strength": "75 mg",
        "company": "Egyptian cardio-aspirin brand",
        "uses": "Antiplatelet secondary prevention when prescribed (not routine primary prevention without advice).",
        "dose_adults": "Usually 75–100 mg once daily after food as prescribed.",
        "dose_children": "Avoid (Reye risk context for aspirin in kids with viral illness).",
        "contra": [
            "Active peptic ulcer/bleeding",
            "Aspirin/NSAID allergy",
            "Severe hepatic failure",
            "Children/adolescents with viral illness",
        ],
        "warnings": "GI bleed risk. Not for pain dosing when used as cardio aspirin without checking total dose.",
        "interactions": "Warfarin, other antiplatelets, SSRIs, NSAIDs (ibuprofen may attenuate effect if poorly timed), alcohol binge.",
        "pregnancy": "Avoid in third trimester; earlier only if prescribed.",
        "breastfeeding": "Low-dose sometimes used — clinician confirm.",
        "sides": "Dyspepsia, bleeding, bronchospasm in sensitive asthmatics.",
        "storage": "Dry; protect from moisture.",
        "supplements": "For pain while on Aspocid prefer paracetamol; avoid OTC ibuprofen unless advised.",
    },
    {
        "file": "36_telfast_120.txt",
        "title": "TELFAST Fexofenadine 120 mg Tablets",
        "brand": "Telfast",
        "inn": "fexofenadine",
        "form": "film-coated tablets",
        "strength": "120 mg",
        "company": "Sanofi (Egypt)",
        "uses": "Allergic rhinitis and chronic idiopathic urticaria (as labelled strengths).",
        "dose_adults": "Often 120 mg once daily for allergic rhinitis (180 mg used for urticaria in some labels).",
        "dose_children": "Age-appropriate lower strengths.",
        "contra": ["Hypersensitivity"],
        "warnings": "Less sedating than older antihistamines, but individual response varies.",
        "interactions": "Antacids containing aluminium/magnesium reduce absorption — separate 2 hours. Fruit juices may reduce absorption — take with water.",
        "pregnancy": "Ask clinician.",
        "breastfeeding": "Ask clinician.",
        "sides": "Headache, drowsiness (uncommon), nausea.",
        "storage": "Below 25–30°C.",
        "supplements": "Take with water, not juice; space antacids.",
    },
    {
        "file": "37_claritine_10.txt",
        "title": "CLARITINE Loratadine 10 mg Tablets",
        "brand": "Claritine",
        "inn": "loratadine",
        "form": "tablets",
        "strength": "10 mg",
        "company": "Bayer/Schering lineage (Egypt OTC allergy)",
        "uses": "Allergic rhinitis and urticaria.",
        "dose_adults": "10 mg once daily.",
        "dose_children": "Syrup dosing by age/weight.",
        "contra": ["Allergy to loratadine"],
        "warnings": "Caution in severe hepatic impairment (dose interval changes).",
        "interactions": "Fewer than sedating antihistamines; still review other CNS drugs.",
        "pregnancy": "Ask pharmacist/doctor.",
        "breastfeeding": "Passes into milk — ask advice.",
        "sides": "Headache, fatigue, dry mouth (usually mild).",
        "storage": "Dry place.",
        "supplements": "Allergen avoidance measures.",
    },
    {
        "file": "38_otrivin_0_1.txt",
        "title": "OTRIVIN Xylometazoline 0.1% Nasal Drops/Spray",
        "brand": "Otrivin",
        "inn": "xylometazoline",
        "form": "nasal spray/drops",
        "strength": "0.1% adult",
        "company": "GSK/Haleon lineage (Egypt)",
        "uses": "Short-term relief of nasal congestion in colds/sinusitis.",
        "dose_adults": "1–2 sprays/drops per nostril up to 2–3 times daily. Max usually 5–7 days.",
        "dose_children": "Use paediatric 0.05% only as labelled.",
        "contra": [
            "After transsphenoidal surgery / dry rhinitis as labelled",
            "Sensitivity to sympathomimetics",
            "Narrow-angle glaucoma caution",
        ],
        "warnings": "Do not use >5–7 days — rebound congestion (rhinitis medicamentosa). Caution in hypertension/hyperthyroidism.",
        "interactions": "MAOIs / other sympathomimetics — caution.",
        "pregnancy": "Short-term if needed after advice; prefer saline first.",
        "breastfeeding": "Short-term likely low systemic — ask pharmacist.",
        "sides": "Nasal dryness/burning, sneezing, rebound congestion with overuse.",
        "storage": "Do not share bottle; keep clean.",
        "supplements": "Isotonic saline sprays are safer for prolonged use.",
    },
    {
        "file": "39_ventolin_inhaler.txt",
        "title": "VENTOLIN Salbutamol Inhaler CFC-free",
        "brand": "Ventolin",
        "inn": "salbutamol (albuterol)",
        "form": "MDI inhaler",
        "strength": "100 micrograms/actuation",
        "company": "GSK (Egypt)",
        "uses": "Reliever for asthma/COPD bronchospasm — acute symptom relief.",
        "dose_adults": "1–2 puffs as needed for symptoms. If needing frequent reliever, escalate asthma plan with clinician.",
        "dose_children": "As prescribed with spacer when recommended.",
        "contra": ["Allergy to salbutamol"],
        "warnings": "Not a substitute for inhaled corticosteroid controllers in persistent asthma. Seek urgent care if poor response.",
        "interactions": "Beta-blockers may antagonize effect; caution with other sympathomimetics.",
        "pregnancy": "Used when needed for asthma control — uncontrolled asthma is riskier.",
        "breastfeeding": "Generally compatible.",
        "sides": "Tremor, tachycardia, headache, nervousness.",
        "storage": "Do not puncture/expose canister to heat.",
        "supplements": "Spacer technique education; peak-flow monitoring if advised.",
    },
    {
        "file": "40_singulair_10.txt",
        "title": "SINGULAIR Montelukast 10 mg Tablets",
        "brand": "Singulair",
        "inn": "montelukast",
        "form": "film-coated tablets",
        "strength": "10 mg",
        "company": "MSD (Egypt)",
        "uses": "Asthma maintenance and allergic rhinitis in appropriate patients — not for acute asthma attacks.",
        "dose_adults": "10 mg once daily in the evening.",
        "dose_children": "Chewables/granules by age.",
        "contra": ["Hypersensitivity"],
        "warnings": "Neuropsychiatric effects (mood/sleep/behaviour changes) — stop and seek advice if occur. Not a reliever inhaler replacement.",
        "interactions": "Gemfibrozil may raise levels; phenobarbital/rifampicin may reduce levels.",
        "pregnancy": "Only if needed.",
        "breastfeeding": "Discuss.",
        "sides": "Headache, abdominal pain; mood/sleep disturbance (important safety signal).",
        "storage": "Keep in original blister (light/moisture sensitive).",
        "supplements": "Continue prescribed inhalers; do not stop ICS abruptly.",
    },
    {
        "file": "41_diflucan_150.txt",
        "title": "DIFLUCAN Fluconazole 150 mg Capsule",
        "brand": "Diflucan",
        "inn": "fluconazole",
        "form": "capsule",
        "strength": "150 mg",
        "company": "Pfizer (Egypt)",
        "uses": "Vaginal candidiasis (often single 150 mg dose) and other fungal infections as prescribed.",
        "dose_adults": "Vaginal thrush: commonly one 150 mg capsule as a single dose. Other infections: multi-day regimens.",
        "dose_children": "Specialist mg/kg regimens.",
        "contra": [
            "Allergy to azoles",
            "Coadministration with drugs contraindicated for QT/CYP reasons on label (e.g. certain combinations)",
            "Pregnancy for most non-urgent indications — avoid single dose thrush treatment in pregnancy without obstetric advice",
        ],
        "warnings": "Hepatotoxicity rare but possible. Many CYP interactions.",
        "interactions": "Warfarin (INR↑), oral sulfonylureas, phenytoin, cyclosporine, some statins, QT drugs — pharmacist check essential.",
        "pregnancy": "Avoid unless specialist benefit/risk.",
        "breastfeeding": "Single dose often compatible; prolonged — discuss.",
        "sides": "Headache, abdominal pain, diarrhoea, rash; rare hepatitis.",
        "storage": "Room temperature dry.",
        "supplements": "For recurrent thrush evaluate antibiotics/diabetes; probiotics optional adjunct.",
    },
    {
        "file": "42_lamisil_250.txt",
        "title": "LAMISIL Terbinafine 250 mg Tablets",
        "brand": "Lamisil",
        "inn": "terbinafine",
        "form": "tablets",
        "strength": "250 mg",
        "company": "Novartis (Egypt)",
        "uses": "Dermatophyte nail/skin infections when systemic therapy indicated.",
        "dose_adults": "Often 250 mg once daily for weeks–months depending on site (nails longer).",
        "dose_children": "Specialist.",
        "contra": ["Chronic/active liver disease", "Terbinafine allergy"],
        "warnings": "Baseline LFTs often recommended. Taste disturbance may be prolonged. Report jaundice/dark urine.",
        "interactions": "CYP2D6 substrates (some antidepressants, beta-blockers); rifampicin; cimetidine.",
        "pregnancy": "Avoid unless necessary.",
        "breastfeeding": "Avoid — excreted in milk.",
        "sides": "Headache, GI upset, rash, taste loss, rare hepatotoxicity.",
        "storage": "Dry place.",
        "supplements": "Avoid alcohol excess during systemic antifungal therapy.",
    },
    {
        "file": "43_duphaston_10.txt",
        "title": "DUPHASTON Dydrogesterone 10 mg Tablets",
        "brand": "Duphaston",
        "inn": "dydrogesterone",
        "form": "film-coated tablets",
        "strength": "10 mg",
        "company": "Abbott (Egypt women's health)",
        "uses": "Progestogen therapy for menstrual disorders, endometriosis support, luteal support, HRT combinations as prescribed.",
        "dose_adults": "Regimen is indication-specific (cyclic vs continuous) — follow specialist prescription exactly.",
        "dose_children": "Not indicated.",
        "contra": [
            "Known/suspected progestogen-dependent malignancy",
            "Undiagnosed vaginal bleeding",
            "Severe liver disease",
            "Allergy",
        ],
        "warnings": "Not contraception. Report new severe headache, vision changes, jaundice, or VTE symptoms.",
        "interactions": "Enzyme inducers (rifampicin, carbamazepine, St John's wort) may reduce effect.",
        "pregnancy": "Used in some obstetric indications only under specialist care.",
        "breastfeeding": "Discuss — limited preferred use.",
        "sides": "Breast tenderness, spotting, nausea, headache, mood change.",
        "storage": "Below 30°C.",
        "supplements": "Do not add OTC hormonal herbals (e.g. wild yam claims) without advice.",
    },
    {
        "file": "44_folic_acid_5.txt",
        "title": "FOLIC ACID 5 mg Tablets (Egyptian generic/branded)",
        "brand": "Folic Acid 5 mg",
        "inn": "folic acid",
        "form": "tablets",
        "strength": "5 mg",
        "company": "Multiple Egyptian manufacturers (common pharmacy SKU)",
        "uses": "Folate deficiency; pregnancy planning/antenatal supplementation protocols; some anemia regimens with B12/iron as indicated.",
        "dose_adults": "Deficiency: often 5 mg daily as prescribed. Pregnancy prevention of NTD: commonly 400 micrograms OTC — 5 mg reserved for higher-risk women as advised.",
        "dose_children": "As prescribed.",
        "contra": ["Untreated B12 deficiency caution — folate may mask haematologic signs"],
        "warnings": "Investigate anemia properly. High-risk pregnancy dosing is clinician-guided.",
        "interactions": "Phenytoin/phenobarbital/primidone levels may be affected; methotrexate regimens are specialist-managed.",
        "pregnancy": "Indicated in planning/pregnancy per risk level.",
        "breastfeeding": "Compatible.",
        "sides": "Rare allergy, GI upset.",
        "storage": "Dry place.",
        "supplements": "Often combined with iron/B12 when diet poor — do not self-megadose indefinitely.",
    },
    {
        "file": "45_ferrotron.txt",
        "title": "FERROTRON Iron Capsules",
        "brand": "Ferrotron",
        "inn": "iron (elemental iron salt as labelled) ± supportive vitamins",
        "form": "capsules",
        "strength": "as labelled elemental iron",
        "company": "Egyptian iron supplement brand",
        "uses": "Iron-deficiency anemia and prevention when dietary intake insufficient / increased demand.",
        "dose_adults": "Usually 1 capsule daily, or as prescribed. Take on empty stomach if tolerated, or with food if GI upset.",
        "dose_children": "Paediatric iron drops preferred.",
        "contra": ["Haemochromatosis", "Iron overload states", "Allergy"],
        "warnings": "Keep away from children — iron overdose is toxic. Stools may turn black.",
        "interactions": "Tea/coffee/calcium/antacids reduce absorption. Separate from levothyroxine, tetracyclines, quinolones by 2–4 hours. PPI may reduce absorption.",
        "pregnancy": "Commonly used when indicated.",
        "breastfeeding": "Compatible.",
        "sides": "Constipation, nausea, epigastric pain, black stools.",
        "storage": "Child-proof; dry place.",
        "supplements": "Vitamin C can help absorption; avoid taking with milk/tea.",
    },
    {
        "file": "46_milga.txt",
        "title": "MILGA Vitamin B1/B6/B12 Tablets",
        "brand": "Milga",
        "inn": "thiamine + pyridoxine + cyanocobalamin",
        "form": "film-coated tablets",
        "strength": "neurotropic B-vitamin combination as labelled",
        "company": "Egyptian neurotropic vitamin brand",
        "uses": "Vitamin B deficiency states; supportive use in neuropathies as adjunct when indicated.",
        "dose_adults": "Often 1 tablet once or twice daily as labelled/prescribed.",
        "dose_children": "Ask pharmacist for age suitability.",
        "contra": ["Allergy to components"],
        "warnings": "Not a stand-alone treatment for severe neurological disease. High-dose B6 chronic use may cause neuropathy — respect labelled maxima.",
        "interactions": "Levodopa interactions possible with B6 in some contexts — check if Parkinson therapy.",
        "pregnancy": "Usually acceptable at labelled doses.",
        "breastfeeding": "Usually acceptable.",
        "sides": "Nausea, rash (rare), urine color change possible with vitamins.",
        "storage": "Dry place away from light.",
        "supplements": "Do not stack multiple high-dose B6 products.",
    },
    {
        "file": "47_smecta.txt",
        "title": "SMECTA Diosmectite Powder Sachets",
        "brand": "Smecta",
        "inn": "diosmectite (smectite)",
        "form": "oral powder sachets",
        "strength": "3 g/sachet typical",
        "company": "Ipsen (Egypt retail)",
        "uses": "Acute diarrhoea adjunct; chronic diarrhoea symptomatic relief in some labelled uses; may help gastroesophageal heartburn in some markets — follow local label.",
        "dose_adults": "Usually 1 sachet three times daily, dissolved in water, for short courses.",
        "dose_children": "Age-banded dosing; ensure rehydration.",
        "contra": ["Fructose intolerance if sweetened accordingly", "Use caution if intestinal obstruction suspected"],
        "warnings": "ORS remains essential in dehydration. Not an antibiotic.",
        "interactions": "Can bind other oral medicines — give other drugs ≥1–2 hours apart.",
        "pregnancy": "Generally acceptable short-term.",
        "breastfeeding": "Generally acceptable.",
        "sides": "Constipation, rare allergy.",
        "storage": "Sachets dry; prepare when needed.",
        "supplements": "Oral rehydration salts first-line companion therapy.",
    },
    {
        "file": "48_enterogermina.txt",
        "title": "ENTEROGERMINA Bacillus clausii Vials/Capsules",
        "brand": "Enterogermina",
        "inn": "Bacillus clausii spores probiotic",
        "form": "oral vials or capsules",
        "strength": "as labelled spore count",
        "company": "Sanofi (Egypt)",
        "uses": "Restoration of intestinal flora; adjunct in diarrhoea and during/after antibiotic courses.",
        "dose_adults": "Often 1–2 vials/capsules daily, or as labelled.",
        "dose_children": "Paediatric dosing common — follow pack.",
        "contra": ["Immunocompromised caution for probiotic use — ask clinician", "Allergy"],
        "warnings": "Rare bacteremia risk in severely immunocompromised patients.",
        "interactions": "Antibiotics: separate by a few hours when possible so spores are not inactivated unnecessarily.",
        "pregnancy": "Generally considered acceptable.",
        "breastfeeding": "Generally considered acceptable.",
        "sides": "Bloating (uncommon).",
        "storage": "Room temperature as labelled; do not freeze vials.",
        "supplements": "Useful companion during Augmentin/Hi-Biotic courses when timed apart.",
    },
    {
        "file": "49_strepsils.txt",
        "title": "STREPSILS Antiseptic Lozenges",
        "brand": "Strepsils",
        "inn": "amylmetacresol + dichlorobenzyl alcohol (classic) / variant actives by SKU",
        "form": "lozenges",
        "strength": "as labelled",
        "company": "Reckitt (Egypt)",
        "uses": "Local symptomatic relief of sore throat.",
        "dose_adults": "1 lozenge every 2–3 hours. Max as labelled (often ≤12/day).",
        "dose_children": "Age minimum usually 6+ years due to choking.",
        "contra": ["Allergy to ingredients", "Young children below age limit"],
        "warnings": "See doctor if severe/persistent throat pain, high fever, or difficulty breathing/swallowing.",
        "interactions": "Local product — minimal systemic interactions.",
        "pregnancy": "Short-term OK if needed.",
        "breastfeeding": "Short-term OK if needed.",
        "sides": "Tongue irritation, taste change, allergy rare.",
        "storage": "Cool dry place; sealed wrap.",
        "supplements": "Warm fluids; Bradozen/Strepsils — pick one lozenge brand at a time.",
    },
    {
        "file": "50_comtrex.txt",
        "title": "COMTREX Cold Tablets (Day/Night variants)",
        "brand": "Comtrex",
        "inn": "paracetamol + chlorpheniramine + pseudoephedrine (typical multi-symptom cold formula; check local SKU)",
        "form": "tablets",
        "strength": "multi-ingredient",
        "company": "BMS/GSK lineage cold brand (Egypt pharmacies)",
        "uses": "Multi-symptom cold relief: fever, aches, runny nose, congestion. Night variants more sedating.",
        "dose_adults": "Follow day/night pack schedule strictly. Do not exceed paracetamol daily maximum across all products.",
        "dose_children": "Adult cold tablets not for children.",
        "contra": [
            "Paracetamol allergy",
            "Severe hypertension",
            "MAOI therapy",
            "Severe hepatic disease",
            "Narrow-angle glaucoma / BPH caution",
        ],
        "warnings": "Drowsiness (especially night). Do not combine with Congestal/Flurest/Sine-Up duplicates. No alcohol.",
        "interactions": "Alcohol, sedatives, MAOIs, other decongestants, other paracetamol products, warfarin (prolonged use).",
        "pregnancy": "Avoid unless advised.",
        "breastfeeding": "Avoid unless advised.",
        "sides": "Sedation, dry mouth, insomnia/nervousness, nausea, raised BP.",
        "storage": "Original blister; dry place.",
        "supplements": "Prefer single-ingredient paracetamol + saline spray when possible to reduce duplicate actives.",
    },
]


def render(d: dict) -> str:
    brand = d["brand"]
    contra = "\n".join(f"- {c}" for c in d["contra"])
    return f"""{d['title']}
Patient Information Leaflet — Egyptian Commercial E2E Corpus
Brand: {brand}
INN / actives: {d['inn']}
Strength / form: {d['strength']} ({d['form']})
Manufacturer / market: {d['company']}
Corpus note: For AlgoRAG retrieval testing. Verify against the official Egyptian PIL/MoH label before clinical use.

1. What {brand} is used for
{d['uses']}

2. Dosage — Adults
{d['dose_adults']}

3. Dosage — Children
{d['dose_children']}

4. Do not take {brand} if
{contra}

5. Warnings and precautions
{d['warnings']}

6. Interactions
{d['interactions']}

7. Pregnancy
{d['pregnancy']}

8. Breastfeeding
{d['breastfeeding']}

9. Supplements and practical tips
{d['supplements']}

10. Possible side effects
{d['sides']}

11. Storage
{d['storage']}
"""


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    index_lines = [
        "# Egyptian commercial leaflets (E2E corpus)",
        "",
        "50 PIL-style leaflets for AlgoRAG testing. Content is typical public market information,",
        "not a substitute for the official package insert.",
        "",
        "| # | File | Brand | INN |",
        "|---|------|-------|-----|",
    ]
    for i, d in enumerate(DRUGS, start=1):
        path = OUT / d["file"]
        path.write_text(render(d), encoding="utf-8")
        index_lines.append(
            f"| {i} | `{d['file']}` | {d['brand']} | {d['inn']} |"
        )
    (OUT / "README.md").write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(DRUGS)} leaflets to {OUT}")


if __name__ == "__main__":
    main()
