from enum import Enum

class ResponseSignal(Enum):

    FILE_VALIDATED_SUCCESS = "file_validate_successfully"
    FILE_TYPE_NOT_SUPPORTED = "file_type_not_supported"
    FILE_SIZE_EXCEEDED = "file_size_exceeded"
    FILE_UPLOAD_SUCCESS = "file_upload_success"
    FILE_UPLOAD_FAILED = "file_upload_failed"
    PROCESSING_SUCCESS = "processing_success"
    PROCESSING_FAILED = "processing_failed"
    NO_FILES_ERROR = "not_found_files"
    FILE_ID_ERROR = "no_file_found_with_this_id"
    PROJECT_NOT_FOUND_ERROR = "project_not_found"
    INSERT_INTO_VECTORDB_ERROR = "insert_into_vectordb_error"
    INSERT_INTO_VECTORDB_SUCCESS = "insert_into_vectordb_success"
    VECTORDB_COLLECTION_RETRIEVED = "vectordb_collection_retrieved"
    VECTORDB_COLLECTION_NOT_FOUND = "vectordb_collection_not_found"
    VECTORDB_SEARCH_ERROR = "vectordb_search_error"
    VECTORDB_SEARCH_SUCCESS = "vectordb_search_success"
    RAG_ANSWER_ERROR = "rag_answer_error"
    RAG_NO_CONTEXT = "rag_no_context"
    RAG_ANSWER_SUCCESS = "rag_answer_success"
    RAG_CLARIFICATION_NEEDED = "rag_clarification_needed"
    DATA_PUSH_TASK_READY="data_push_task_ready"
    PROCESS_AND_PUSH_WORKFLOW_READY="process_and_push_workflow_ready"
    TASK_STATUS_RETRIEVED = "task_status_retrieved"
    PROJECT_CREATED_SUCCESS = "project_created_success"
    PROJECT_LIST_SUCCESS = "project_list_success"
    PROJECT_RETRIEVED_SUCCESS = "project_retrieved_success"
    PROJECT_NAME_REQUIRED = "project_name_required"
    PROJECT_PROMPT_RETRIEVED = "project_prompt_retrieved"
    PROJECT_PROMPT_UPDATED = "project_prompt_updated"